#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lints and Formats Code.
echo "👀 Serchinng and fixing Lint issues 🛠️"
echo "👀 Serchinng and fixing Format issues 🎨"
yarn lint-stage
echo "👀 Linting thinggs up 🧑‍💻"
npx lint-staged